echo "Hi! This is a shell program, so you should know how to use those."
echo ""
echo "This is your path - you want to put buatae.sh in one of these directories to run it easily"
echo "${PATH}"
echo ""
echo "Then buatae needs a few resource files, helpscreen, brushes (glyphs) and palettes."
echo ""
echo "You can use a GIMP .gpl palette if it uses decimal color values."
echo ""
echo "So move and rename ./config_buatae directory  to /home/\$USER/.config/buatae"
echo ""
echo "Then you can start buatae.sh from the terminal with buatae.sh"
